version: "master-{build}"

os: Visual Studio 2017

environment:
  bundle_gemfile: ci.gemfile

  matrix:
    - RUBY_VERSION: 25
      chef_version: "master"
    - RUBY_VERSION: 26
      chef_version: "master"

clone_folder: c:\projects\knife-windows
clone_depth: 1
branches:
  only:
    - master
    - 2-stable

install:
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-document || true
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rake
